version: '3'
services:
    php-apache:
        build:
            ./docker/php/dev
        container_name: sran-apache-server-test
        ports:
            - 80:80
        volumes:
            - ./:/var/www/sran:z
            - ./docker/apache/vhosts:/etc/apache2/sites-enabled
        links:
            - 'mariadb'
        environment:
            TZ: "Europe/Bucharest"
        image: sran/dev:v4

    mariadb:
        image: mariadb:10.3
        container_name: sran-mysql-server-test
        environment:
            TZ: "Europe/Bucharest"
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
            MYSQL_ROOT_PASSWORD: ''
            MYSQL_DATABASE: 'sran_test'
            DATABASE_UR: 'mysql://root@sran-mysql-server-test:3306/sran_test'
        ports:
            - 3306:3306

volumes:
    mariadb:
