version: '3'
services:
    nginx:
        image: nginx:latest
        container_name: sran-nginx-server
        ports:
            - 80:80
        volumes:
            - ./:/var/www/sran:z
            - ./docker/nginx/site.conf:/etc/nginx/conf.d/site.conf
        links:
            - php
    php:
        build:
            ./docker/php/prod
        container_name: sran-php-server
        volumes:
            - ./:/var/www/sran:z
        links:
            - 'mariadb'
        environment:
            TZ: "Europe/Bucharest"
        image: sran/prod:v8

    mariadb:
        image: mariadb:10.3
        container_name: sran-mysql-server
        volumes:
            - mariadb:/var/lib/mysql
        environment:
            TZ: "Europe/Bucharest"
            MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
            MYSQL_ROOT_PASSWORD: 'sran_root'
            MYSQL_USER: 'sran_user'
            MYSQL_PASSWORD: 'sran_password'
            MYSQL_DATABASE: 'sran'

volumes:
    mariadb:
